using System.Data.Entity;

namespace Expert.Modules.Customers
{
    public partial class CustomersView : DevExpress.XtraEditors.XtraUserControl
    {
        Data.ExpertContext dbContext;
        public CustomersView()
        {
            InitializeComponent();

            RightToLeft = Properties.Settings.Default.RightToLeft;

            GetData();
        }

        private void GetData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new Data.ExpertContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Customers.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                CustomersBindingSource.DataSource = dbContext.Customers.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void NewButton_Click(object sender, System.EventArgs e)
        {
            // new customer id
            //IDTextEdit.Text = (dbContext.Customers.MaxAsync(c => c.ID).Result + 1).ToString();

            // initialize new customer object to list
            CustomersBindingSource.AddNew();
            First_nameTextEdit.Focus();
        }

        private void SaveButton_Click(object sender, System.EventArgs e)
        {
            // end binding list editting state
            CustomersBindingSource.EndEdit();
            // save data to database
            dbContext.SaveChanges();
        }

        private void ResetButton_Click(object sender, System.EventArgs e)
        {
            // refresh data bindings
            CustomersBindingSource.ResetBindings(true);
        }
    }
}
