using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace Expert.Modules.Customers
{
    public partial class CustomersList : DevExpress.XtraEditors.XtraUserControl
    {
        public CustomersList()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Expert.Data.ExpertContext dbContext = new Expert.Data.ExpertContext();

            dbContext.Customers.Load();
            var customers = dbContext.Categories.Local.ToList();
            var customer = customers.FirstOrDefault(c => c.ID == 1) ?? null;
            if (customer != null) MessageBox.Show(customer.Name);
            else return;


            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Categories.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                categoriesBindingSource.DataSource = dbContext.Categories.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
